const footerContainer = document.createElement('footer');
footerContainer.classList.add('footer');

const footerContent = document.createElement('div');
footerContent.id = 'footerContent';
footerContent.innerHTML = `
<div class='heroLogo'>WW</div>
<h4>Indulge in a Waffle Wonderland At Willow's Waffles!</h4>
<p>Filler text generated by chatGPT</p>
`;

footerContainer.appendChild(footerContent);

document.body.appendChild(footerContainer);
